### ISSUE TITLE
Passing SPIClass in the constructor

### ISSUE THREAD

**Issue by opseb** [wollewald/ADS1220_WE#4]
Thank you very much for this library. 

ESP32 has got two SPI interfaces namely VSPI (default) and HSPI. When passing a custom SPIClass to use the HSPI interface the setup gets stuck after reading a single value. After several attempts to assign different pins and avoiding restricted pins, I found that there is a method ( void ADS1220_WE::command(uint8_t cmd) ) in the file ADS1220_WE.cpp where there the global SPI is used instead of custom member_spi assigned in the constructor .

Changing the line SPI.transfer(cmd) to _spi->transfer(cmd) solves the problem when assigning a different SPI interface in ESP32. 

Kindly advice if this change is correct and if it could be a possible bug fix

**Comment by wollewald** [comment]
@opseb , thank you! I I have absolutely no idea why I left this single SPI instruction as SPI.transfer() and not like all others to _spi->transfer(). Will change this immediately.

**Comment by wollewald** [comment]
Since I changed the code and haven't heard anything I consider this issue to be completed.

**Comment by opseb** [comment]
Sorry for late reply. The code has been no problem since the code was fixed.
